# Generated by Django 3.2.25 on 2024-05-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingredientimage_extracted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredientimage',
            name='extracted',
        ),
    ]
